language: scala
sudo: false

jdk:
  - oraclejdk8

script:
  - sbt +publishLocal

cache:
  directories:
    - $HOME/.ivy2/cache

before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/io.play-rconf
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/io.play-rconf
  - rm -rf $HOME/.ivy2/cache/com.github.play-rconf
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.github.play-rconf

  # Delete all ivy data files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
